---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170816122823"
editor:
  name: "AddAtomistAgent"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.10.1"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "89f78bf484ca28be4c634e8b93b720f3b45f7d8f"
    sha: "89f78bf"
  parameters:
    - "slackTeam": "T6ZP98M61"

