logging:
  level:
    com.atomist.spring.agent: DEBUG
atomist:
  enabled: true
  debug: true
  url: 'https://webhook.atomist.com/atomist/application/teams/T6ZP98M61'
  environment:
    domain: '${DOMAIN:development}'
    pod: '${HOSTNAME:${random.value}}'
